<?php

/**
 * @file
 * Contains ckeditor_googlesearch.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ckeditor_clearbody_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ckeditor_clearbody':
      $output = '';
      $output .= '<h3>' . t('Ckeditor Clear Body') . '</h3>';
      $output .= '<p>' . t('The module adds a Clear Body html button to the editor toolbar.') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Settings') . '</dt>';
      $output .= '<dd>' . t('In the <a href=":text-formats">text formats</a> that use ckeditor, move the Clear Body icon into the active toolbar.', [':text-formats' => \Drupal::url('filter.admin_overview')]) . '</dd>';
      $output .= '</dl>';
      return $output;

    default:
  }
}
